# Generated by Django 3.1 on 2022-03-16 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='joined_date',
            new_name='date_joined',
        ),
    ]
