# Generated by Django 4.0.3 on 2022-04-05 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_account_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='image',
        ),
    ]
