# Generated by Django 4.0.3 on 2022-04-09 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_profilepicture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfilePicture',
        ),
    ]
