# Generated by Django 4.0.3 on 2022-03-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_off_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='off_price',
            field=models.FloatField(null=True),
        ),
    ]
