# Generated by Django 4.0.1 on 2022-03-22 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_product_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='store.product'),
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='store.variation')),
            ],
        ),
    ]
