# Generated by Django 4.0.1 on 2022-03-22 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_variation_product_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='value',
        ),
    ]
