# Generated by Django 4.0.1 on 2022-03-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_value_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='has_images',
            field=models.BooleanField(default=False),
        ),
    ]
