# Generated by Django 4.0.3 on 2022-03-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_variation_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='variation',
            field=models.ManyToManyField(to='store.variation'),
        ),
    ]
