# Generated by Django 4.0.3 on 2022-03-24 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_cartitem_variation_value'),
        ('store', '0020_remove_variation_product_product_variation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='variation',
        ),
        migrations.AddField(
            model_name='variation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/values'),
        ),
        migrations.AddField(
            model_name='variation',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='store.product'),
        ),
        migrations.RemoveField(
            model_name='variation',
            name='value',
        ),
        migrations.AddField(
            model_name='variation',
            name='value',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Value',
        ),
    ]
