# Generated by Django 4.0.3 on 2022-03-24 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_remove_product_variation_variation_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='image',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='value',
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/values')),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='store.variation')),
            ],
        ),
    ]
