# Generated by Django 4.0.1 on 2022-03-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_remove_cartitem_value_cartitem_variation'),
        ('store', '0022_remove_variation_image_remove_variation_value_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='category',
            new_name='name',
        ),
        migrations.AddField(
            model_name='variation',
            name='value',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Value',
        ),
    ]
