# Generated by Django 4.0.1 on 2022-06-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_remove_product_stock_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='total',
            field=models.IntegerField(),
        ),
    ]
