# Generated by Django 4.0.1 on 2022-06-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_alter_stock_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='value',
            field=models.ManyToManyField(blank=True, null=True, to='store.Value'),
        ),
    ]
