# Generated by Django 4.0.1 on 2022-07-16 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_alter_reviewrating_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_variant',
        ),
    ]
