# Generated by Django 4.0.1 on 2022-07-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_gallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'galleries'},
        ),
        migrations.AlterField(
            model_name='gallery',
            name='images',
            field=models.ImageField(max_length=255, upload_to=''),
        ),
    ]
