# Generated by Django 4.0.3 on 2022-03-17 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_off_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='off_price',
        ),
    ]
