# Generated by Django 4.0.1 on 2022-03-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_remove_variation_image_remove_variation_value_value'),
        ('cart', '0004_alter_cartitem_variation_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='variation_value',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='value',
            field=models.ManyToManyField(blank=True, to='store.Value'),
        ),
    ]
