# Generated by Django 4.0.1 on 2022-03-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_rename_name_variation_category_and_more'),
        ('cart', '0006_remove_cartitem_value_cartitem_variation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='variation',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='value',
            field=models.ManyToManyField(blank=True, to='store.Value'),
        ),
    ]
