# Generated by Django 4.0.1 on 2022-06-07 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_orderproduct_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='variation',
        ),
    ]
